name: Generate terraform docs
on:
  - pull_request

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.ref }}

    - name: Render terraform docs and push changes back to PR
      uses: terraform-docs/gh-actions@v0.10.0
      with:
        working-dir: rds,S3,S3_log_bucket,vpc
        output-file: README.md
        output-format: markdown
        output-method: replace
        git-commit-message: "docs(terraform-docs): automated update"
        git-push: "true"
        template: |
          <!--- BEGIN\_TF\_DOCS --->
          <!--- END\_TF\_DOCS --->
